export const wTextSetting = {
    name: '文本',
    type: 'w-text',
    uuid: -1,
    editable: false,
    left: 0,
    top: 0,
    transform: '',
    lineHeight: 1.5,
    letterSpacing: 0,
    fontSize: 24,
    zoom: 1,
    fontClass: {
        alias: '思源黑体',
        id: 1001,
        value: 'Noto Sans SC',
        url: '',
    },
    fontFamily: 'Noto Sans SC',
    fontWeight: 'normal',
    fontStyle: 'normal',
    writingMode: 'horizontal-tb',
    textDecoration: 'none',
    color: '#000000ff',
    textAlign: 'left',
    textAlignLast: 'left',
    text: '',
    opacity: 1,
    backgroundColor: '',
    parent: '-1',
    record: {
        width: 0,
        height: 0,
        minWidth: 0,
        minHeight: 0,
        dir: 'horizontal',
    },
};
