export const wQrcodeSetting = {
    name: '二维码',
    type: 'w-qrcode',
    uuid: -1,
    width: 300,
    height: 300,
    left: 0,
    top: 0,
    zoom: 1,
    transform: '',
    radius: 0,
    opacity: 1,
    parent: '-1',
    url: '',
    dotType: 'classy',
    dotColorType: 'single',
    dotRotation: 270,
    dotColor: '#35495E',
    dotColor2: '#67e8f9',
    value: 'https://kunqiong.design',
    setting: [],
    record: {
        width: 0,
        height: 0,
        minWidth: 10,
        minHeight: 10,
        dir: 'all',
    },
};
